In [ ]:
# importing the libraries
import pandas as pd
import numpy as np

# for reading and displaying images
from skimage.io import imread
import matplotlib.pyplot as plt
%matplotlib inline

# for creating validation set
from sklearn.model_selection import train_test_split

# for evaluating the model
from sklearn.metrics import accuracy_score
from tqdm import tqdm

# PyTorch libraries and modules
import torch
from torch.autograd import Variable
from torch.nn import Linear, ReLU, CrossEntropyLoss, Sequential, Conv2d, MaxPool2d, Module, Softmax, BatchNorm2d, Dropout
from torch.optim import Adam, SGD

In [ ]:
import torch
a=torch.tensor([0,1,2.1],dtype=torch.int32)
b=a.view(3,1)
print(a)
c=torch.tensor([[1,2],[2,3],[3,4]])
print(c.type)
#new_float_tensor = old_int_tensor.type(torch.FloatTensor)

tensor([0, 1, 2], dtype=torch.int32)
<built-in method type of Tensor object at 0x7fde3e674ee8>


In [ ]:
a=torch.tensor(2.0,requires_grad=True)
b=a**3
b.backward()
print(a.grad)

tensor(12.)


In [ ]:
a=np.array([1,2,3])
b=torch.from_numpy(a)
c=b.numpy()
print(b)

tensor([1, 2, 3])


In [ ]:
# Basic Linear Output
import torch

b=torch.tensor(-1.0,requires_grad=True)
w=torch.tensor(2.0,requires_grad=True)
x=torch.tensor([1.0])
def forward(x):
  y=w*x+b
  return y
y_hat=forward(x)
print(y_hat)


tensor([1.], grad_fn=<AddBackward0>)


In [ ]:
#Basic Linear output using Linear - Pytorch Tensor

from torch.nn import Linear
torch.manual_seed(1)
lr = Linear(in_features=1, out_features=1, bias=True)
print("Parameters w and b: ", list(lr.parameters()))
print("Python dictionary: ",lr.state_dict())
print("keys: ",lr.state_dict().keys())
print("values: ",lr.state_dict().values())
x = torch.tensor([[1.0], [2.0]])
yhat = lr(x)
print("The prediction: ", yhat)

Parameters w and b:  [Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]
Python dictionary:  OrderedDict([('weight', tensor([[0.5153]])), ('bias', tensor([-0.4414]))])
keys:  odict_keys(['weight', 'bias'])
values:  odict_values([tensor([[0.5153]]), tensor([-0.4414])])
The prediction:  tensor([[0.0739],
        [0.5891]], grad_fn=<AddmmBackward>)


In [ ]:

m = torch.nn.Linear(20, 30)
input = torch.randn(128, 20)
output = m(input)
print(output.size())

torch.Size([128, 30])
